language: ruby

before_install:
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml

rvm:
  - 2.1.3

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace

script:
  - RAILS_ENV=test bundle exec rspec
