common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  pool: 5
  timeout: 5000

development:
  <<: *common
  database: orienteering_development
  password: y0l0test
  template: template0

test:
  <<: *common
  database: orienteering_test
  password: y0l0test
  template: template0

production:
  <<: *common
  database: orienteering_production
  password:
  template: template0
